# Generated by Django 5.1.3 on 2024-12-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja', '0003_stanowisko_osoba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
