# Generated by Django 5.1.2 on 2025-01-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja', '0006_alter_osoba_data_dodania'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('change_person_owner', 'Pozwala przypisać inną osobę do obiektu Person.'), ('change_assign_to_team', 'Pozwala przypisać osobę do innej drużyny.')]},
        ),
        migrations.AddField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
